---
title: "week2_caret"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
```


```{r load packages}
library(caret)
library(kernlab)
library(data.table)
library(magrittr)
library(purrr)
```

## `caret` functions

- Preprocessing
- Data splitting
- Train / test / predict
- Model comparison

Gitbook: https://topepo.github.io/caret/index.html

## Algorithms

- Comes from different packages (`MASS`, `stats`, `gbm`, `mda`, ...)
- `caret::predict(model_object, ...)`

## SPAM Example

```{r}
library(caret)
library(kernlab)
library(data.table)
library(magrittr)
data(spam)
spam %>% setDT
head(spam)

# Splitting
in_train <- createDataPartition(y = spam$type, times = 1, p = .75)
training <- spam[in_train$Resample1,]; dim(training)
testing <- spam[-in_train$Resample1,]; dim(testing)

# Fit a model
set.seed(32343)
model_fit <- train(type ~., data = training, method = "glm")
model_fit
```

```{r}
# str(model_fit, max.level = 1)
# model_fit$finalModel

# Prediction
pred <- predict(model_fit, newdata = testing)
head(pred)
```

```{r}
# Confusion matrix
confusionMatrix(data = pred, reference = testing$type)
```


## Data Slicing

```{r}
# CV: K-fold
folds <- createFolds(training, k = 10, returnTrain = TRUE) # default return testing
map_int(folds, length)
folds[[1]] %>% head
```



